var use4 = svg('use')
use4.setAttribute('xlink:href', '#sym-octagon')
use4.setAttribute('href', '#sym-octagon')
use4.setAttribute('x', '40')
use4.setAttribute('y', '110')
use4.setAttribute('width', '30')
use4.setAttribute('height', '30')
svgEl.appendChild(use4)
